name: 'Notify Metadata Changes'
description: 'Notifies RabbitMQ about Metadata Changes to domain.yaml or data_product.yaml'
runs:
  using: "composite"
  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@17.2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.5' # Version range or exact version of a Python version to use, using SemVer's version range syntax
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/actions/scripts/requirements.txt
      shell: bash
    - name: Send Message to RabbitMQ
      run: |
        python .github/actions/scripts/send.py ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash
